name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: crazy-max/ghaction-github-runtime@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Dry run publish
        run: pnpm -r publish --dry-run

      - name: Fild dist directories
        id: find-dists
        run: |
          echo 'dirs<<EOF' >> $GITHUB_OUTPUT
          for dir in $(find . -type d -name "*dist" -not -path "*/node_modules/*"); do
            echo $dir >> $GITHUB_OUTPUT
          done
          echo 'EOF' >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: dists
          path: ${{ steps.find-dists.outputs.dirs }}
